const dict = new Map([
  ['être', 'to be'],
  ['avoir', 'to have'],
  ['faire', 'to do/make'],
  ['pouvoir', 'to be able to'],
  ['dire', 'to say/tell'],
  ['aller', 'to go'],
  ['venir', 'to come'],
  ['voir', 'to see'],
  ['savoir', 'to know (information)'],
  ['devoir', 'to have to/must'],
  ['vouloir', 'to want'],
  ['prendre', 'to take'],
  ['donner', 'to give'],
  ['trouver', 'to find'],
  ['falloir', 'to be necessary'],
  ['parler', 'to speak'],
  ['aimer', 'to like/love'],
  ['croire', 'to believe'],
  ['regarder', 'to watch/look'],
  ['entendre', 'to hear'],
  ['comprendre', 'to understand'],
  ['penser', 'to think'],
  ['mettre', 'to put'],
  ['connaître', 'to know (be acquainted with)'],
  ['travailler', 'to work'],
  ['jouer', 'to play'],
  ['sortir', 'to go out'],
  ['rester', 'to stay/remain'],
  ['partir', 'to leave'],
  ['arriver', 'to arrive'],
  ['passer', 'to pass/spend'],
  ['rencontrer', 'to meet'],
  ['appeler', 'to call'],
  ['venir', 'to come'],
  ['revenir', 'to come back'],
  ['aller', 'to go'],
  ['envoyer', 'to send'],
  ['ouvrir', 'to open'],
  ['fermer', 'to close'],
  ['lire', 'to read'],
  ['écrire', 'to write'],
  ['acheter', 'to buy'],
  ['vendre', 'to sell'],
  ['manger', 'to eat'],
  ['boire', 'to drink'],
  ['vivre', 'to live'],
  ['dormir', 'to sleep'],
  ['regarder', 'to look/watch'],
  ['écouter', 'to listen'],
  ['attendre', 'to wait'],
  ['aimer', 'to like/love'],
  ['adorer', 'to adore'],
  ['haïr', 'to hate'],
  ['parler', 'to speak'],
  ['chanter', 'to sing'],
  ['danser', 'to dance'],
  ['étudier', 'to study'],
  ['apprendre', 'to learn'],
  ['enseigner', 'to teach'],
  ['voyager', 'to travel'],
  ['travailler', 'to work'],
  ['dessiner', 'to draw'],
  ['peindre', 'to paint'],
  ['jouer', 'to play'],
  ['gagner', 'to win/earn'],
  ['perdre', 'to lose'],
  ['courir', 'to run'],
  ['marcher', 'to walk'],
  ['nager', 'to swim'],
  ['sauter', 'to jump'],
  ['voler', 'to steal/fly'],
  ['cuisiner', 'to cook'],
  ['nettoyer', 'to clean'],
  ['laver', 'to wash'],
  ["s'asseoir", 'to sit down'],
  ['se lever', 'to stand up'],
  ['se coucher', 'to go to bed'],
  ['se réveiller', 'to wake up'],
  ['se brosser', 'to brush'],
  ['se laver', 'to wash oneself'],
  ['se doucher', 'to take a shower'],
  ['se changer', 'to change clothes'],
  ['se promener', 'to take a walk'],
  ['se perdre', 'to get lost'],
  ['se retrouver', 'to meet up'],
  ['se dépêcher', 'to hurry up'],
  ['se calmer', 'to calm down'],
  ['se détendre', 'to relax'],
  ['se taire', 'to be quiet'],
  ['se souvenir', 'to remember'],
  ["s'habiller", 'to get dressed']
]);