const dict = new Map([
  ["abolish", "huỷ bỏ"],
  ["abortion", "sự sẩy thai"],
  ["absence", "sự vắng mặt"],
  ["absent", "vắng mặt"],
  ["absorb", "thấm, thu hút, hấp thụ, thu nạp"],
  ["abstract", "trừu tượng, tác phẩm trừu tượng, bản tóm tắt"],
  ["absurd", "ngớ ngẩn"],
  ["abuse", "lạm dụng, sỉ nhục"],
  ["academy", "học viện"],
  ["accelerate", "tăng tốc"],
  ["accent", "giọng, sự nhấn mạnh, dấu nhấn phát âm, dấu trọng âm, nhấn mạnh"],
  ["acceptance", "sự chấp thuận"],
  ["accessible", "có thể tới được, gần gũi"],
  ["accidentally", "ngẫu nhiên"],
  ["accommodate", "cung cấp chỗ ở cho ai, đáp ứng"],
  ["accommodation", "chỗ ở"],
  ["accomplish", "hoàn thành"],
  ["accomplishment", "tài năng, sự hoàn thành"],
  ["accordingly", "phù hợp với, do đó"],
  ["accountability", "trách nhiệm"],
  ["accountable", "chịu trách nhiệm"],
  ["accountant", "nhân viên kế toán"],
  ["accumulate", "thu gom"],
  ["accumulation", "sự tích luỹ"],
  ["accuracy", "sự chính xác"],
  ["accurately", "một cách chính xác"],
  ["accusation", "sự buộc tội"],
  ["accused", "bị cáo"],
  ["acid", "chất chua, mỉa mai, có chứa axít, a-xít"],
  ["acquisition", "sự giành được, cái giành được"],
  ["acre", "mẫu Anh"],
  ["activate", "làm hoạt động"],
  ["activation", "sự hoạt hoá, hoạt hóa, khởi động"],
  ["activist", "nhà hoạt động"],
  ["acute", "cấp tính, lớn, nhạy bén, tinh"],
  ["adaptation", "sự điều chỉnh"],
  ["addiction", "sự nghiện"],
  ["additionally", "bổ sung, ngoài ra, thêm nữa"],
  ["adequate", "đủ, vừa đủ"],
  ["adequately", "một cách đầy đủ"],
  ["adhere", "bám, trung thành"],
  ["adjacent", "liền kề"],
  ["adjust", "điều chỉnh, chỉnh"],
  ["adjustment", "sự điều chỉnh"],
  ["administer", "quản lý, thực thi, phân phát"],
  ["administrative", "thuộc về quản lý"],
  ["administrator", "nhà quản lý"],
  ["admission", "sự cho phép vào, sự thừa nhận, nhập viện"],
  ["adolescent", "vị thành niên, trẻ vị thành niên"],
  ["adoption", "nhận làm con nuôi, sự chọn, sự làm theo"],
  ["adverse", "bất lợi"],
  ["advocate", "người ủng hộ, luật sư bào chữa, tán thành"],
  ["aesthetic", "thuộc mỹ học"],
  ["affection", "yêu mến"],
  ["affordable", "giá cả phải chăng"],
  ["aftermath", "hậu quả"],
  ["aged", "già"],
  ["aggression", "sự xâm lược"],
  ["agricultural", "thuộc nông nghiệp"],
  ["agriculture", "nông nghiệp"],
  ["aide", "trợ lý"],
  
]);
