const dict = new Map([
  ["người", "person"],
  ["nước", "water"],
  ["thời gian", "time"],
  ["cái", "thing"],
  ["gia đình", "family"],
  ["học sinh", "student"],
  ["trường học", "school"],
  ["sách", "book"],
  ["bàn", "table"],
  ["ghế", "chair"],
  ["công việc", "work"],
  ["tiền", "money"],
  ["chìa khóa", "key"],
  ["cửa", "door"],
  ["cửa sổ", "window"],
  ["phòng", "room"],
  ["ngôi nhà", "house"],
  ["thịt", "meat"],
  ["rau", "vegetable"],
  ["trái cây", "fruit"],
  ["cà phê", "coffee"],
  ["trà", "tea"],
  ["bánh mì", "bread"],
  ["sữa", "milk"],
  ["nước cam", "orange juice"],
  ["bánh", "cake"],
  ["mì", "noodles"],
  ["điện thoại", "phone"],
  ["máy tính", "computer"],
  ["internet", "internet"],
  ["áo", "shirt"],
  ["quần", "pants"],
  ["giày", "shoes"],
  ["mũ", "hat"],
  ["túi", "bag"],
  ["vật nuôi", "pet"],
  ["chó", "dog"],
  ["mèo", "cat"],
  ["ngựa", "horse"],
  ["con cá", "fish"],
  ["chim", "bird"],
  ["sách vở", "notebook"],
  ["bút", "pen"],
  ["tập", "notebook (exercise book)"],
  ["tờ báo", "newspaper"],
  ["tivi", "TV"],
  ["xe đạp", "bicycle"],
  ["ô tô", "car"],
  ["tàu", "train"],
  ["máy bay", "airplane"],
  ["người lái xe", "driver"],
  ["mùa", "season"],
  ["ngày", "day"],
  ["tuần", "week"],
  ["tháng", "month"],
  ["năm", "year"],
  ["lịch", "calendar"],
  ["giờ", "hour"],
  ["phút", "minute"],
  ["giây", "second"],
  ["đồng hồ", "clock"],
  ["thực phẩm", "food"],
  ["sở thích", "hobby"],
  ["du lịch", "travel"],
  ["học", "study"],
  ["dạy", "teach"],
  ["cuộc sống", "life"],
  ["tình yêu", "love"],
  ["bạn bè", "friends"],
  ["niềm vui", "joy"],
  ["nỗi buồn", "sorrow"],
  ["tâm trí", "mind"],
  ["sức khỏe", "health"],
  ["vấn đề", "problem"],
  ["giải pháp", "solution"],
  ["lý do", "reason"],
  ["kết quả", "result"],
  ["mục tiêu", "goal"],
  ["cơ hội", "opportunity"],
  ["nguy cơ", "danger"],
  ["bước", "step"],
  ["cảm giác", "feeling"],
  ["nhà hàng", "restaurant"],
  ["quán cà phê", "coffee shop"],
  ["chợ", "market"],
  ["cửa hàng", "store"],
  ["siêu thị", "supermarket"],
  ["bệnh viện", "hospital"],
  ["ngân hàng", "bank"],
  ["trung tâm thương mại", "shopping mall"],
  ["sân bay", "airport"],
  ["bãi biển", "beach"],
  ["núi", "mountain"],
  ["rừng", "forest"],
  ["hồ", "lake"],
  ["sông", "river"],
  ["biển", "sea"],
  ["đảo", "island"],
  ["thành phố", "city"],
  ["vùng", "region"],
  ["quốc gia", "country"],
  ["thủ đô", "capital"],
  ["khu phố", "neighborhood"],
  ["đường phố", "street"],
  ["quảng trường", "square"],
  ["công viên", "park"],
  ["vườn", "garden"]
]);
