const dict = new Map([
  ['speak (parler)', 'parle parles parle parlons parlez parlent'],
  ['eat (manger)', 'mange manges mange mangeons mangez mangent'],
  ['live (vivre)', 'vis vis vit vivons vivez vivent'],
  ['be (être)', 'suis es est sommes êtes sont'],
  ['have (avoir)', 'ai as a avons avez ont'],
  ['go (aller)', 'vais vas va allons allez vont'],
  ['do (faire)', 'fais fais fait faisons faites font'],
  ['see (voir)', 'vois vois voit voyons voyez voient'],
  ['know (savoir)', 'sais sais sait savons savez savent'],
  ['say (dire)', 'dis dis dit disons dites disent'],
  ['can (pouvoir)', 'peux peux peut pouvons pouvez peuvent'],
  ['give (donner)', 'donne donnes donne donnons donnez donnent'],
  ['come (venir)', 'viens viens vient venons venez viennent'],
  ['take (prendre)', 'prends prends prend prenons prenez prennent'],
  ['make (faire)', 'fais fais fait faisons faites font'],
  ['know (connaître)', 'connais connais connaît connaissons connaissez connaissent'],
  ['want (vouloir)', 'veux veux veut voulons voulez veulent'],
  ['work (travailler)', 'travaille travailles travaille travaillons travaillez travaillent'],
  ['like (aimer)', 'aime aimes aime aimons aimez aiment'],
  ['understand (comprendre)', 'comprends comprends comprend comprenons comprenez comprennent'],
  ['go out (sortir)', 'sors sors sort sortons sortez sortent'],
  ['see (regarder)', 'regarde regardes regarde regardons regardez regardent'],
  ['need (avoir besoin de)', 'ai besoin de as besoin de a besoin de avons besoin de avez besoin de ont besoin de'],
  ['put (mettre)', 'mets mets met mettons mettez mettent'],
  ['become (devenir)', 'deviens deviens devient devenons devenez deviennent'],
  ['stay (rester)', 'reste restes reste restons restez restent'],
  ['ask (demander)', 'demande demandes demande demandons demandez demandent'],
  ['call (appeler)', 'appelle appelles appelle appelons appelez appellent'],
  ['follow (suivre)', 'suis suis suit suivons suivez suivent'],
  ['finish (finir)', 'finis finis finit finissons finissez finissent'],
]);