const dict = new Map([
  ['je', 'I'],
  ['tu', 'you (singular informal)'],
  ['il', 'he'],
  ['elle', 'she'],
  ['on', 'one/we'],
  ['nous', 'we'],
  ['vous', 'you (plural/formal)'],
  ['ils', 'they (masculine)'],
  ['elles', 'they (feminine)'],
  ['me', 'me'],
  ['te', 'you (singular informal)'],
  ['se', 'oneself'],
  ['nous', 'us'],
  ['vous', 'you'],
  ['le', 'him/it (direct object)'],
  ['la', 'her/it (direct object)'],
  ['les', 'them (direct object)'],
  ['lui', 'him/her (indirect object)'],
  ['leur', 'them (indirect object)'],
  ['moi', 'me'],
  ['toi', 'you'],
  ['soi', 'oneself'],
  ['eux', 'them'],
  ['eux-mêmes', 'themselves'],
  ['elle-même', 'herself'],
  ['eux-mêmes', 'themselves'],
  ['celui', 'the one (masculine)'],
  ['celle', 'the one (feminine)'],
  ['ceux', 'those (masculine)'],
  ['celles', 'those (feminine)'],
  ['qui', 'who/whom'],
  ['que', 'that/which'],
  ['quoi', 'what'],
  ['dont', 'whose'],
  ['où', 'where'],
  ['le mien', 'mine'],
  ['la mienne', 'mine'],
  ['les miens', 'mine'],
  ['les miennes', 'mine'],
  ['le tien', 'yours (singular informal)'],
  ['la tienne', 'yours (singular informal)'],
  ['les tiens', 'yours (singular informal)'],
  ['les tiennes', 'yours (singular informal)'],
  ['le sien', 'his/hers/its'],
  ['la sienne', 'his/hers/its'],
  ['les siens', 'his/hers/its'],
  ['les siennes', 'his/hers/its'],
  ['le nôtre', 'ours'],
  ['la nôtre', 'ours'],
  ['les nôtres', 'ours'],
  ['le vôtre', 'yours (plural/formal)'],
  ['la vôtre', 'yours (plural/formal)'],
  ['les vôtres', 'yours (plural/formal)'],
  ['le leur', 'theirs'],
  ['la leur', 'theirs'],
  ['les leurs', 'theirs'],
  ['à', 'to/at'],
  ['de', 'from/of'],
  ['pour', 'for'],
  ['avec', 'with'],
  ['sans', 'without'],
  ['chez', 'at (someone\'s place)'],
  ['dans', 'in/inside'],
  ['sur', 'on/upon'],
  ['sous', 'under/below'],
  ['en', 'in/on'],
  ['par', 'by/through'],
  ['vers', 'towards'],
  ['pendant', 'during'],
  ['contre', 'against'],
  ['autour', 'around'],
  ['entre', 'between/among'],
  ['jusque', 'until'],
  ['envers', 'towards'],
  ['devant', 'in front of'],
  ['derrière', 'behind'],
  ['à côté de', 'next to/beside'],
  ['près de', 'near/close to'],
  ['loin de', 'far from'],
  ['au-dessus de', 'above'],
  ['au-dessous de', 'below'],
  ['parmi', 'among'],
  ['à travers', 'through'],
  ['au milieu de', 'in the middle of'],
  ['à cause de', 'because of'],
  ['grâce à', 'thanks to'],
  ['selon', 'according to'],
  ['quant à', 'as for/regarding'],
  ['au sujet de', 'about/regarding'],
  ['à l\'égard de', 'towards/regarding'],
  ['concernant', 'concerning'],
  ['durant', 'during'],
  ['depuis', 'since'],
  ['vers', 'towards'],
  ['jusqu\'à', 'until'],
  ['à partir de', 'from/since'],
  ['au-delà de', 'beyond'],
  ['au-dessus de', 'above'],
  ['au-dessous de', 'below'],
  ['à l\'intérieur de', 'inside'],
  ['à l\'extérieur de', 'outside'],
  ['au sujet de', 'about/regarding'],
  ['autour de', 'around'],
  ['près de', 'near/close to'],
  ['loin de', 'far from'],
  ['en face de', 'in front of'],
  ['à l\'opposé de', 'opposite'],
  ['au nord de', 'north of'],
  ['au sud de', 'south of'],
  ['à l\'est de', 'east of'],
  ['à l\'ouest de', 'west of'],
  ['au-dessous de', 'below'],
  ['au-dessus de', 'above'],
  ['par rapport à', 'in relation to'],
  ['vis-à-vis de', 'vis-à-vis'],
  ['afin de', 'in order to'],
  ['à l\'abri de', 'sheltered from'],
  ['en face de', 'opposite/in front of'],
  ['à travers', 'through'],
  ['parmi', 'among'],
  ['avec', 'with'],
  ['sans', 'without'],
  ['pour', 'for'],
  ['contre', 'against'],
  ['depuis', 'since/from'],
  ['selon', 'according to'],
  ['grâce à', 'thanks to'],
  ['en dehors de', 'outside of'],
  ['jusqu\'à', 'until'],
  ['après', 'after'],
  ['avant', 'before'],
  ['pendant', 'during'],
  ['entre', 'between'],
  ['parmi', 'among'],
  ['avec', 'with'],
  ['pour', 'for'],
  ['contre', 'against'],
  ['sans', 'without'],
  ['depuis', 'since'],
  ['chez', 'at (someone\'s place)'],
  ['autour de', 'around'],
  ['au-dessus de', 'above'],
  ['au-dessous de', 'below'],
  ['parmi', 'among'],
  ['envers', 'towards'],
  ['devant', 'in front of'],
  ['derrière', 'behind'],
  ['à côté de', 'next to/beside'],
  ['près de', 'near/close to'],
  ['loin de', 'far from'],
  ['dans', 'in/inside'],
  ['sur', 'on/upon'],
  ['sous', 'under/below'],
  ['en', 'in/on'],
  ['par', 'by/through'],
  ['vers', 'towards'],
  ['au milieu de', 'in the middle of'],
  ['à cause de', 'because of'],
  ['grâce à', 'thanks to'],
  ['selon', 'according to'],
  ['quant à', 'as for/regarding'],
  ['au sujet de', 'about/regarding'],
  ['à l\'égard de', 'towards/regarding'],
  ['concernant', 'concerning'],
  ['durant', 'during'],
  ['depuis', 'since'],
  ['vers', 'towards'],
  ['jusqu\'à', 'until'],
  ['à partir de', 'from/since'],
  ['au-delà de', 'beyond'],
  ['au-dessus de', 'above'],
  ['au-dessous de', 'below'],
  ['à l\'intérieur de', 'inside'],
  ['à l\'extérieur de', 'outside'],
  ['au sujet de', 'about/regarding'],
  ['autour de', 'around'],
  ['près de', 'near/close to'],
  ['loin de', 'far from'],
  ['en face de', 'in front of'],
  ['à l\'opposé de', 'opposite'],
  ['au nord de', 'north of'],
  ['au sud de', 'south of'],
  ['à l\'est de', 'east of'],
  ['à l\'ouest de', 'west of'],
  ['au-dessous de', 'below'],
  ['au-dessus de', 'above'],
  ['par rapport à', 'in relation to'],
  ['vis-à-vis de', 'vis-à-vis'],
  ['afin de', 'in order to'],
  ['à l\'abri de', 'sheltered from'],
  ['et', 'and'],
  ['ou', 'or'],
  ['mais', 'but'],
  ['donc', 'so'],
  ['or', 'now'],
  ['ni', 'neither/nor'],
  ['car', 'for/because'],
  ['puisque', 'since/as'],
  ['lorsque', 'when'],
  ['si', 'if'],
  ['parce que', 'because'],
  ['afin que', 'so that'],
  ['pendant que', 'while'],
  ['quoique', 'although'],
  ['comme', 'as'],
  ['ainsi que', 'as well as'],
  ['quand', 'when'],
  ['tant que', 'as long as'],
  ['tandis que', 'while'],
  ['au cas où', 'in case'],
  ['de manière que', 'so that'],
  ['pourvu que', 'provided that'],
  ['avant que', 'before'],
  ['après que', 'after'],
  ['bien que', 'although'],
  ['soit que...soit que', 'either...or'],
  ['quoique...que', 'no matter'],
  ['puis', 'then'],
  ['autrement', 'otherwise'],
  ['sinon', 'otherwise'],
  ['de sorte que', 'so that'],
  ['afin de', 'in order to'],
  ['par conséquent', 'consequently'],
  ['en somme', 'in short'],
  ['c\'est pourquoi', 'that\'s why'],
  ['en revanche', 'on the other hand'],
  ['pour commencer', 'to begin with'],
  ['en tout cas', 'in any case'],
  ['c\'est-à-dire', 'that is to say'],
  ['en d\'autres termes', 'in other words'],
  ['pour conclure', 'to conclude'],
  ['en effet', 'indeed'],
  ['cependant', 'however'],
  ['en gros', 'in general'],
  ['pour cette raison', 'therefore'],
  ['en outre', 'furthermore'],
  ['également', 'also'],
  ['ensuite', 'then'],
  ['par ailleurs', 'furthermore'],
  ['quand même', 'even if'],
  ['finalement', 'finally'],
  ['pourtant', 'however'],
  ['qu\'est-ce que', 'what'],
  ['le', 'the (masculine singular)'],
  ['la', 'the (feminine singular)'],
  ['les', 'the (plural)'],
  ['un', 'a/an (masculine singular)'],
  ['une', 'a/an (feminine singular)'],
  ['des', 'some (plural)'],
  ['du', 'some (masculine singular)'],
  ['de la', 'some (feminine singular)'],
  ['de l\'', 'some (before a vowel or silent h)'],
  ['au', 'to the (masculine singular)'],
  ['à la', 'to the (feminine singular)'],
  ['aux', 'to the (plural)'],
  ['d\'un', 'of a (masculine singular)'],
  ['d\'une', 'of a (feminine singular)'],
  ['de', 'of/from'],
]);