const dict = new Map([
  ['être', 'to be'],
  ['avoir', 'to have'],
  ['faire', 'to do'],
  ['dire', 'to say'],
  ['aller', 'to go'],
  ['pouvoir', 'to be able to'],
  ['vouloir', 'to want'],
  ['voir', 'to see'],
  ['savoir', 'to know'],
  ['venir', 'to come'],
  ['devoir', 'to have to'],
  ['prendre', 'to take'],
  ['donner', 'to give'],
  ['trouver', 'to find'],
  ['falloir', 'to be necessary'],
  ['parler', 'to speak'],
  ['mettre', 'to put'],
  ['penser', 'to think'],
  ['aimer', 'to like'],
  ['comprendre', 'to understand'],
  ['partir', 'to leave'],
  ['croire', 'to believe'],
  ['venir', 'to come'],
  ['rendre', 'to return'],
  ['vivre', 'to live'],
  ['voir', 'to see'],
  ['demander', 'to ask'],
  ['travailler', 'to work'],
  ['acheter', 'to buy'],
  ['appeler', 'to call'],
  ['jouer', 'to play'],
  ['devenir', 'to become'],
  ['sortir', 'to go out'],
  ['rester', 'to stay'],
  ['sembler', 'to seem'],
  ['porter', 'to wear'],
  ['entendre', 'to hear'],
  ['arriver', 'to arrive'],
  ['compter', 'to count'],
  ['écrire', 'to write'],
  ['connaître', 'to know'],
  ['perdre', 'to lose'],
  ['reprendre', 'to take back'],
  ['choisir', 'to choose'],
  ['souhaiter', 'to wish'],
  ['apprendre', 'to learn'],
  ['regarder', 'to watch'],
  ['passer', 'to pass'],
  ['retrouver', 'to find again'],
  ['former', 'to form'],
  ['écouter', 'to listen'],
  ['servir', 'to serve'],
  ['demander', 'to ask'],
  ['établir', 'to establish'],
  ['reconnaître', 'to recognize'],
  ['occuper', 'to occupy'],
  ['présenter', 'to present'],
  ['permettre', 'to allow'],
  ['garder', 'to keep'],
  ['reprendre', 'to take back'],
  ['quitter', 'to leave'],
  ['montrer', 'to show'],
  ['temps', 'time'],
  ['année', 'year'],
  ['jour', 'day'],
  ['homme', 'man'],
  ['femme', 'woman'],
  ['enfant', 'child'],
  ['maison', 'house'],
  ['ville', 'city'],
  ['pays', 'country'],
  ['ami', 'friend'],
  ['famille', 'family'],
  ['travail', 'work'],
  ['école', 'school'],
  ['étudiant', 'student'],
  ['professeur', 'teacher'],
  ['livre', 'book'],
  ['chambre', 'room'],
  ['restaurant', 'restaurant'],
  ['nourriture', 'food'],
  ['voiture', 'car'],
  ['argent', 'money'],
  ['journaux', 'newspapers'],
  ['temps', 'weather'],
  ['musique', 'music'],
  ['film', 'film'],
  ['problème', 'problem'],
  ['marché', 'market'],
  ['magasin', 'store'],
  ['route', 'road'],
  ['arbre', 'tree'],
  ['fleur', 'flower'],
  ['animal', 'animal'],
  ['mer', 'sea'],
  ['rivière', 'river'],
  ['montagne', 'mountain'],
  ['soleil', 'sun'],
  ['lune', 'moon'],
  ['étoile', 'star'],
  ['ciel', 'sky'],
  ['nuit', 'night'],
  ['matin', 'morning'],
  ['soir', 'evening'],
  ['couleur', 'color'],
  ['image', 'picture'],
  ['musée', 'museum'],
  ['exposition', 'exhibition'],
  ['histoire', 'history'],
  ['art', 'art'],
  ['langue', 'language'],
  ['maison', 'home'],
  ['jardin', 'garden'],
  ['parc', 'park'],
  ['pont', 'bridge'],
  ['bateau', 'boat'],
  ['train', 'train'],
  ['avion', 'plane'],
  ['ville', 'city'],
  ['bâtiment', 'building'],
  ['hôtel', 'hotel'],
  ['chambre', 'room'],
  ['lit', 'bed'],
  ['table', 'table'],
  ['chaise', 'chair'],
  ['porte', 'door'],
  ['fenêtre', 'window'],
  ['mur', 'wall'],
  ['plafond', 'ceiling'],
  ['sol', 'floor'],
  ['escalier', 'stair'],
  ['clé', 'key'],
  ['voiture', 'car'],
  ['route', 'road'],
  ['feu', 'fire'],
  ['eau', 'water'],
  ['air', 'air'],
  ['terre', 'earth'],
  ['ciel', 'sky'],
  ['forêt', 'forest'],
  ['plante', 'plant'],
  ['fleur', 'flower'],
  ['herbe', 'grass'],
  ['rocher', 'rock'],
  ['animal', 'animal'],
  ['oiseau', 'bird'],
  ['poisson', 'fish'],
  ['chat', 'cat'],
  ['chien', 'dog'],
  ['cheval', 'horse'],
  ['vache', 'cow'],
  ['ferme', 'farm'],
  ['travail', 'work'],
  ['argent', 'money'],
  ['commerce', 'commerce'],
  ['marché', 'market'],
  ['magasin', 'store'],
  ['produit', 'product'],
  ['service', 'service'],
  ['restaurant', 'restaurant'],
  ['nourriture', 'food'],
  ['boisson', 'beverage'],
  ['café', 'coffee'],
  ['thé', 'tea'],
  ['vin', 'wine'],
  ['bière', 'beer'],
  ['eau', 'water'],
  ['jus', 'juice'],
  ['santé', 'health'],
  ['médecin', 'doctor'],
  ['hôpital', 'hospital'],
  ['maladie', 'illness'],
  ['remède', 'remedy'],
  ['pharmacie', 'pharmacy']
]);