const dict = new Map([
  ["bramble", "bụi gai"],
  ["stamina", "sức bền"],
  ["endurance", "sự chịu đựng"],
  ["flicker", "lung linh"],
  ["transition", "chuyển đổi"],
  ["obscure", "tối nghĩa"],
  ["obsessed", "ám ảnh"],
  ["abandon", "từ bỏ"],
  ["allegory", "ngụ ngôn"],
  ["cave", "hang động"],
  ["concept", "khái niệm"],
  ["to present", "trình bày"],
  ["metaphor", "phép ẩn dụ"],
  ["used to", "đã từng"],
  ["the effect", "tác động"],
  ["perception", "nhận thức"],
  ["ignorance", "sự thiếu hiểu biết"],
  ["prisoner", "tù nhân"],
  ["to be chained", "bị xiềng xích"],
  ["blank", "trống rỗng"],
  ["cast", "ném"],
  ["to pass in front", "đi qua trước"],
  ["behind", "phía sau"],
  ["to represent", "đại diện"],
  ["to be freed", "được giải thoát"],
  ["to be exposed", "bị phơi bày"],
  ["to be blinded by", "bị làm mù bởi"],
  ["gradually", "dần dần"],
  ["vivid", "sống động"],
  ["to symbolize", "tượng trưng"],
  ["enlightenment", "sự giác ngộ"],
  ["struggle", "cuộc đấu tranh"],
  ["to share", "chia sẻ"],
  ["discovery", "sự khám phá"],
  ["remaining", "còn lại"],
  ["to reject", "từ chối"],
  ["to cling to", "bám vào"],
  ["familiar", "quen thuộc"],
  ["unimaginable", "không thể tưởng tượng"]
]);
