const dict = new Map([
  ['peidra', 'stone'],
  ['estaban', 'they were'],
  ['orgullosos', 'proud'],
  ['decir', 'to say'],
  ['eran', 'they were'],
  ['de', 'of'],
  ['las ltimas', 'last'],
  ['se esperaria', 'would be expected'],
  ['encontrar', 'to find'],
  ['relacionadas', 'related'],
  ['con', 'with'],
  ['algo', 'something'],
  ['porque', 'because'],
  ['no esteban', 'they were'],
  ['para', 'for'],
  ['tales', 'such'],
  ['tonterias', 'nonsense'],
  ['era', 'was'],
  ['el', 'the'],
  ['director de', 'director of'],
  ['empresa', 'company'],
  ['llamada', 'called'],
  ['que', 'that'],
  ['fabricaba', 'manufactured'],
  ['talardos', 'overalls'],
  ['corpulento', 'stout'],
  ['rollizo', 'chubby'],
  ['casi', 'almost'],
  ['sin', 'without'],
  ['cuello', 'neck'],
  ['aunque', 'although'],
  ['un bigote', 'a mustache'],
  ['inmenso', 'enormous'],
  ['era', 'was'],
  ['delgada', 'slender'],
  ['rubia', 'blonde'],
  ['tenia', 'had'],
  ['el doble de', 'twice the'],
  ['largo', 'length'],
  ['habitual', 'usual'],
  ['resultaba', 'was'],
  ['util', 'useful'],
  ['ya', 'already'],
  ['pasaba', 'spent'],
  ['mayor parte', 'majority'],
  ['del', 'of the'],
  ['tiempo', 'time'],
  ['estirándolo', 'stretching it'],
  ['por', 'over'],
  ['encima', 'above'],
  ['las vallas', 'the fences'],
  ['los jardines', 'the gardens'],
  ['para', 'to'],
  ['espiar a', 'spy on'],
  ['sus', 'their'],
  ['vecinos', 'neighbors'],
  ['tenian', 'they had'],
  ['ellos', 'them'],
  ['no habia', 'there was no'],
  ['mejor', 'better'],
  ['sobrevivio', 'survived'],
  ['todo', 'everything'],
  ['querian', 'they wanted'],
  ['tambien', 'also'],
  ['guardaban', 'kept'],
  ['meyor', 'greater'],
  ['temor', 'fear'],
  ['descubriesen', 'they were discovered'],
  ['soportado', 'endured'],
  ['se supiera', 'it was known'],
  ['veian', 'they saw'],
  ['desde', 'from'],
  ['hacia', 'towards'],
  ['tanto', 'so'],
  ['asi', 'like this'],
  ['fingia', 'pretended'],
  ['marido', 'husband'],
  ['completo', 'complete'],
  ['inutil', 'useless'],
  ['mas', 'more'],
  ['opuesto a', 'opposite to'],
  ['puderia', 'could'],
  ['estremacian', 'they were horrified'],
  ['al', 'at'],
  ['pensar', 'thinking'],
  ['dirian', 'they would say'],
  ['apareciesen', 'they appeared'],
  ['acera', 'sidewalk'],
  ['Sabían', 'They knew'],
  ['nunca', 'never'],
  ['lo habían visto', 'they had seen him'],
  ['mantener', 'to keep'],
  ['alejados', 'away'],
  ['se juntara', 'they got together'],
  ['aquel', 'that'],
  ['cuando', 'when'],
  ['se despertaron', 'they woke up'],
  ['sombrío', 'gloomy'],
  ['gris', 'gray'],
  ['martes', 'Tuesday'],
  ['nuestra', 'our'],
  ['comienza', 'begins'],
  ['nublado', 'cloudy'],
  ['sugiriera', 'suggested'],
  ['acontecimientos', 'events'],
  ['poco', 'shortly'],
  ['después', 'after'],
  ['tendrían lugar', 'would take place'],
  ['canturreaba', 'he hummed'],
  ['mientras', 'while'],
  ['se ponía', 'he put on'],
  ['corbata', 'tie'],
  ['más', 'more'],
  ['sosa', 'bland'],
  ['parloteaba', 'chattered'],
  ['alegremente', 'happily'],
  ['instalaba', 'he set up'],
  ['ruidoso', 'noisy'],
  ['la trona', 'the high chair'],
  ['ninguno', 'none'],
  ['vio', 'saw'],
  ['gran', 'big'],
  ['búho', 'owl'],
  ['pardo', 'brown'],
  ['pasaba volando', 'flew by'],
  ['por la ventana', 'by the window'],
  ['cogió', 'picked up'],
  ['maletín', 'briefcase'],
  ['beso a', 'kissed'],
  ['mejilla', 'cheek'],
  ['trató de', 'tried to'],
  ['despedirse', 'say goodbye'],
  ['pudo', 'could'],
  ['aunque', 'although'],
  ['ya', 'already'],
  ['un berrinche', 'a tantrum'],
  ['estaba arrojando', 'was throwing'],
  ['contra', 'against'],
  ['las paredes', 'the walls'],
  ['dijo', 'said'],
  ['entre dientes', 'under his breath'],
  ['salía de', 'was coming out of'],
  ['se metió', 'he entered'],
  ['se alejó', 'he walked away'],
  ['al llegar', 'upon reaching'],
  ['esquina', 'corner'],
  ['percibió', 'he noticed'],
  ['primer', 'first'],
  ['indicio', 'sign'],
  ['sucedía', 'was happening'],
  ['raro', 'strange'],
  ['estaba mirando', 'was looking'],
  ['no se dio cuenta', 'he didn\'t realize'],
  ['volvió', 'he turned'],
  ['mirar', 'to look'],
  ['otra vez', 'again'],
  ['había estado pensando', 'had been thinking'],
  ['debía haber sido', 'must have been'],
  ['parpadeo', 'blinked'],
  ['contempló', 'looked at'],
  ['este', 'this'],
  ['le devolvió la mirada', 'stared back at him'],
  ['daba la vuelta', 'turned around'],
  ['subía', 'was going up'],
  ['el espejo', 'the mirror'],
  ['el rótulo', 'the sign'],
  ['no podía ser', 'it couldn\'t be'],
  ['no saben leer', 'they can\'t read'],
  ['negó', 'denied'],
  ['pedido', 'request'],
  ['conseguir', 'to get'],
  ['afueras', 'outskirts'],
  ['aparto', 'I parked'],
  ['esperaba', 'was waiting'],
  ['embotellamiento', 'traffic jam'],
  ['dejar', 'to leave'],
  ['advertir', 'to warn'],
  ['vestida', 'dressed'],
  ['llevaba', 'was wearing'],
  ['los conjuntos', 'the outfits'],
  ['tamborileó', 'tapped'],
  ['dedos', 'fingers'],
  ['sobre', 'on'],
  ['volante', 'steering wheel'],
  ['mirada', 'gaze'],
  ['poso', 'settled'],
  ['desconocidos', 'strangers'],
  ['cerca', 'near'],
  ['cuchicheaban', 'whispered'],
  ['entre sí', 'to each other'],
  ['excitados', 'excited'],
  ['se enfureció', 'became furious'],
  ['darse', 'to give oneself'],
  ['incluso', 'even'],
  ['valor', 'courage'],
  ['publicitaria', 'advertising'],
  ['se sentaba', 'sat'],
  ['espaldas', 'back'],
  ['hubiera hecho', 'would have done'],
  ['había costado', 'had cost'],
  ['señalaban', 'pointed'],
  ['boca', 'mouth'],
  ['abierta', 'open'],
  ['aves', 'birds'],
  ['desfilaban', 'paraded'],
  ['tras', 'behind'],
  ['embargo', 'however'],
  ['gritó', 'shouted'],
  ['hizo', 'made'],
  ['volvió', 'turned'],
  ['estirar', 'stretch'],
  ['piernas', 'legs'],
  ['dirigirse', 'to head'],
  ['enfrente', 'across'],
  ['había olvidado', 'had forgotten'],
  ['lado', 'side'],
  ['miró', 'looked'],
  ['enfadado', 'angry'],
  ['susurraba', 'whispered'],
  ['agitación', 'agitation'],
  ['llevaba', 'carried'],
  ['moneda', 'coin'],
  ['rosquilla', 'doughnut'],
  ['bolsa', 'bag'],
  ['papel', 'paper'],
  ['alcanzó', 'reached'],
  ['oír', 'to hear']
]);