const dict = new Map([
  ['persona', 'person'],
  ['tiempo', 'time'],
  ['año', 'year'],
  ['mano', 'hand'],
  ['día', 'day'],
  ['vida', 'life'],
  ['parte', 'part'],
  ['casa', 'house'],
  ['mundo', 'world'],
  ['amigo', 'friend'],
  ['padre', 'father'],
  ['madre', 'mother'],
  ['trabajo', 'work'],
  ['noche', 'night'],
  ['calle', 'street'],
  ['amor', 'love'],
  ['ciudad', 'city'],
  ['cuerpo', 'body'],
  ['mes', 'month'],
  ['historia', 'history'],
  ['mujer', 'woman'],
  ['gente', 'people'],
  ['lugar', 'place'],
  ['ojo', 'eye'],
  ['mañana', 'morning'],
  ['familia', 'family'],
  ['hombre', 'man'],
  ['nombre', 'name'],
  ['mamá', 'mom'],
  ['país', 'country'],
  ['música', 'music'],
  ['cabeza', 'head'],
  ['cama', 'bed'],
  ['voz', 'voice'],
  ['casa', 'home'],
  ['agua', 'water'],
  ['aire', 'air'],
  ['hermano', 'brother'],
  ['foto', 'photo'],
  ['sol', 'sun'],
  ['mano', 'hand'],
  ['semana', 'week'],
  ['niño', 'child'],
  ['puerta', 'door'],
  ['escuela', 'school'],
  ['profesor', 'teacher'],
  ['palabra', 'word'],
  ['hermana', 'sister'],
  ['mente', 'mind'],
  ['noche', 'evening'],
  ['padre', 'parent'],
  ['trabajo', 'job'],
  ['coche', 'car'],
  ['ropa', 'clothes'],
  ['película', 'movie'],
  ['color', 'color'],
  ['maestro', 'master'],
  ['problema', 'problem'],
  ['animal', 'animal'],
  ['teléfono', 'phone'],
  ['biblioteca', 'library'],
  ['dios', 'god'],
  ['idea', 'idea'],
  ['oído', 'ear'],
  ['silencio', 'silence'],
  ['mesa', 'table'],
  ['minuto', 'minute'],
  ['hijo', 'son'],
  ['amor', 'passion'],
  ['momento', 'moment'],
  ['mujer', 'wife'],
  ['voz', 'sound'],
  ['libro', 'book'],
  ['calle', 'road'],
  ['cabeza', 'mind'],
  ['tarde', 'afternoon'],
  ['historia', 'story'],
  ['mes', 'period'],
  ['lección', 'lesson'],
  ['ciudad', 'town'],
  ['trabajo', 'employment'],
  ['arte', 'art'],
  ['dolor', 'pain'],
  ['muerte', 'death'],
  ['ordenador', 'computer'],
  ['diente', 'tooth'],
  ['cara', 'face'],
  ['ventana', 'window'],
  ['voz', 'vocal'],
  ['cuerpo', 'torso'],
  ['estudiante', 'student'],
  ['idea', 'concept'],
  ['foto', 'photograph'],
  ['carne', 'meat'],
  ['salud', 'health'],
  ['madre', 'mom'],
  ['hermano', 'sibling'],
  ['mesa', 'desk'],
  ['ser', 'to be'],
  ['estar', 'to be'],
  ['tener', 'to have'],
  ['hacer', 'to do'],
  ['decir', 'to say'],
  ['ir', 'to go'],
  ['ver', 'to see'],
  ['saber', 'to know'],
  ['poder', 'to be able to'],
  ['poner', 'to put'],
  ['dar', 'to give'],
  ['haber', 'to have'],
  ['querer', 'to want'],
  ['venir', 'to come'],
  ['decir', 'to tell'],
  ['pasar', 'to pass'],
  ['pensar', 'to think'],
  ['encontrar', 'to find'],
  ['sentir', 'to feel'],
  ['hablar', 'to speak'],
  ['llevar', 'to carry'],
  ['deber', 'to owe'],
  ['trabajar', 'to work'],
  ['creer', 'to believe'],
  ['comer', 'to eat'],
  ['vivir', 'to live'],
  ['esperar', 'to wait'],
  ['amar', 'to love'],
  ['recibir', 'to receive'],
  ['caminar', 'to walk'],
  ['buscar', 'to search'],
  ['entender', 'to understand'],
  ['jugar', 'to play'],
  ['tomar', 'to take'],
  ['dejar', 'to leave'],
  ['conocer', 'to know'],
  ['llegar', 'to arrive'],
  ['empezar', 'to start'],
  ['seguir', 'to follow'],
  ['mirar', 'to look'],
  ['escuchar', 'to listen'],
  ['esperar', 'to hope'],
  ['ver', 'to watch'],
  ['aprender', 'to learn'],
  ['escribir', 'to write'],
  ['sentar', 'to sit'],
  ['permitir', 'to allow'],
  ['cerrar', 'to close'],
  ['viajar', 'to travel'],
  ['ayudar', 'to help'],
  ['pensar', 'to plan'],
  ['pagar', 'to pay'],
  ['beber', 'to drink'],
  ['leer', 'to read'],
  ['comprender', 'to understand'],
  ['cantar', 'to sing'],
  ['correr', 'to run'],
  ['abrir', 'to open'],
  ['soñar', 'to dream'],
  ['preferir', 'to prefer'],
  ['terminar', 'to finish'],
  ]);