const dict = new Map([
  ['por', 'over'],
  ['hacia', 'towards'],
  ['despertar', 'wake up'],
  ['coger', 'pick up'],
  ['arrojar', 'throw'],
  ['saler', 'come out'],
  ['meterse', 'get into'],
  ['suceder', 'happen'],
  ['parpadear', 'blink'],
  ['conseguir', 'to get'],
  ['aparto', 'push away'],
  ['los conjuntos', 'the outfits'],
  ['tamborileó', 'chattering'],
  ['dedo', 'finger'],
  ['sobre', 'on'],
  ['volante', 'steering wheel'],
  ['poso', 'sediment (osadok)'],
  ['valor', 'courage'],
  ['publicitaria', 'advertising'],
  ['espalda', 'back'],
  ['costar', 'cost'],
  ['señalar', 'point'],
  ['desfilar', 'parade, march'],
  ['tras', 'behind'],
  ['embargo', 'however'],
  ['enfrente', 'across'],
  ['lado', 'side'],
  ['enfadado', 'angry'],
  ['susurrar', 'whisper'],
  ['agitación', 'agitation'],
  ['alcanzar', 'reach'],
  ['quedarse', 'stay'],
  ['contenerse', 'hold back'],
  ['apresurar', 'hurry'],
  ['cruzar', 'cross'],
  ['echar', 'throw'],
  ['cambiar', 'change'],
  ['peinar', 'brush hair'],
  ['comportarse', 'behave'],
  ['sobrino', 'nephew'],
  ['valer', 'worth'],
  ['pena', 'regret'],
  ['trastornarse', 'upset'],
  ['ante', 'before'],
  ['cualquier', 'any'],
  ['reprochar', 'reproach'],
  ['modos', 'manners'],
  ['edificio', 'building'],
  ['chocar', 'collide'],
  ['tambalearse', 'stagger'],
  ['caer', 'fall'],
  ['disgustado', 'displeased'],
  ['rostro', 'face'],
  ['amplia', 'wide'],
  ['alegrarse', 'to be glad'],
  ['quedar', 'remain'],
  ['helado', 'frozen'],
  ['fuera', 'outside'],
  ['fuese', 'were'],
  ['desconcertado', 'perplexed'],
  ['presutatse', 'hurry'],
  ['subir', 'go up'],
  ['desear', 'wish'],
  ['suyas', 'theirs'],
  ['antes', 'before'],
  ['aprobar', 'approve'],
  ['sentar', 'sit'],
  ['muro', 'wall'],
  ['mismo', 'same'],
  ['alrededor', 'around'],
  ['voz', 'voice'],
  ['alta', 'high'],
  ['seguir', 'continue'],
  ['cenar', 'have dinner'],
  ['contar', 'count'],
  ['comportar', 'to behave'],
  ['acostarse', 'go to bed'],
  ['sala', 'room'],
  ['noticiero', 'news'],
  ['pese', 'despite'],
  ['cazar', 'hunt'],
  ['ver', 'see'],
  ['cientos', 'hundreds'],
  ['avisos', 'notices'],
  ['sobre', 'about'],
  ['vuelo', 'flight'],
  ['salida', 'exit'],
  ['cambiar', 'change'],
  ['horario', 'schedule'],
  ['locutor', 'announcer'],
  ['lluvia', 'rain'],
  ['mostrar', 'show'],
  ['televidentes', 'viewers'],
  ['apartado', 'paragraph'],
]);