const dict = new Map([
  ['homme', 'man'],
  ['femme', 'woman'],
  ['enfant', 'child'],
  ['ami', 'friend'],
  ['mère', 'mother'],
  ['père', 'father'],
  ['frère', 'brother'],
  ['sœur', 'sister'],
  ['maison', 'house'],
  ['chien', 'dog'],
  ['chat', 'cat'],
  ['table', 'table'],
  ['chaise', 'chair'],
  ['livre', 'book'],
  ['école', 'school'],
  ['ville', 'city'],
  ['voiture', 'car'],
  ['travail', 'work'],
  ['temps', 'time'],
  ['argent', 'money'],
  ['jour', 'day'],
  ['nuit', 'night'],
  ['main', 'hand'],
  ['œil', 'eye'],
  ['terre', 'earth'],
  ['ciel', 'sky'],
  ['fleur', 'flower'],
  ['porte', 'door'],
  ['fenêtre', 'window'],
  ['vélo', 'bicycle'],
  ['boisson', 'drink'],
  ['musique', 'music'],
  ['film', 'movie'],
  ['amour', 'love'],
  ['le', 'the'],
  ['de', 'of'],
  ['un', 'a/an'],
  ['être', 'to be'],
  ['et', 'and'],
  ['à', 'to/at'],
  ['avoir', 'to have'],
  ['ne', 'not'],
  ['je', 'I'],
  ['le', 'the'],
  ['que', 'that'],
  ['ce', 'this'],
  ['pas', 'not'],
  ['pour', 'for'],
  ['dans', 'in'],
  ['qui', 'who'],
  ['sur', 'on/upon'],
  ['se', 'oneself'],
  ['avec', 'with'],
  ['mais', 'but'],
  ['par', 'by'],
  ['il', 'he'],
  ['au', 'to the'],
  ['être', 'to be'],
  ['plus', 'more'],
  ['faire', 'to do/make'],
  ['son', 'his/her'],
  ['comme', 'like/as'],
  ['je', 'I'],
  ['les', 'the'],
  ['en', 'in'],
  ['pour', 'for'],
  ['dire', 'to say'],
  ['elle', 'she'],
  ['du', 'of/from the'],
  ['tout', 'all'],
  ['nous', 'we'],
  ['vous', 'you'],
  ['vous', 'you'],
  ['faire', 'to do/make'],
  ['savoir', 'to know'],
  ['sur', 'on/upon'],
  ['nouveau', 'new'],
  ['leur', 'their'],
  ['venir', 'to come'],
  ['très', 'very'],
  ['bien', 'well'],
  ['voir', 'to see'],
  ['même', 'same/even'],
  ['ses', 'his/her'],
  ['sans', 'without'],
  ['alors', 'so/then'],
  ['toi', 'you'],
  ['ici', 'here'],
  ['deux', 'two'],
  ['se', 'oneself'],
  ['quand', 'when'],
  ['ou', 'or'],
  ['parler', 'to speak'],
  ['moins', 'less'],
  ['lui', 'him/her'],
  ['donc', 'so/therefore'],
  ['prendre', 'to take'],
  ['notre', 'our'],
  ['rien', 'nothing'],
  ['aussi', 'also'],
  ['tout', 'everything'],
  ['mettre', 'to put'],
  ['autre', 'other'],
  ['on', 'one/we'],
  ['quelque', 'some'],
  ['temps', 'time'],
  ['trouver', 'to find'],
  ['donner', 'to give'],
  ['ça', 'that/it'],
  ['grand', 'big'],
  ['bon', 'good'],
  ['venir', 'to come'],
  ['là', 'there'],
  ['petit', 'small'],
  ['devoir', 'to have to'],
  ['parce', 'because'],
  ['prendre', 'to take'],
  ['travail', 'work'],
  ['avant', 'before'],
  ['dire', 'to say'],
  ['home', 'home'],
  ['chose', 'thing'],
  ['voir', 'to see'],
  ['même', 'same/even'],
  ['homme', 'man'],
  ['moment', 'moment'],
  ['fois', 'time'],
  ['partir', 'to leave'],
  ['femme', 'woman'],
  ['place', 'place'],
  ]);