const dict = new Map([
  ["que", "that, what"],
  ["no", "no, not"],
  ["a", "to, at"],
  ["de", "of, from"],
  ["la", "the (feminine)"],
  ["y", "and"],
  ["me", "me, myself"],
  ["es", "is (he/she/it)"],
  ["lo", "it, him"],
  ["qué", "what?"],
  ["el", "the (masculine)"],
  ["en", "in, on"],
  ["por", "by, for"],
  ["se", "himself, herself, itself"],
  ["con", "with"],
  ["un", "a, an (masculine)"],
  ["ya", "already, now"],
  ["para", "for, to"],
  ["mi", "my"],
  ["una", "a, an (feminine)"],
  ["está", "is (he/she/it)"],
  ["los", "the (masculine, plural)"],
  ["si", "if"],
  ["las", "the (feminine, plural)"],
  ["más", "more"],
  ["del", "of the, from the"],
  ["yo", "I"],
  ["pero", "but"],
  ["le", "him, her, it (indirect object)"],
  ["eso", "that (neuter)"],
  ["todo", "all, everything"],
  ["como", "like, as, how"],
  ["muy", "very"],
  ["su", "his, her, its, their"],
  ["o", "or"],
  ["al", "to the, at the"],
  ["así", "like this, like that, so"],
  ["esta", "this (feminine)"],
  ["son", "are (they)"],
  ["te", "you (informal, object)"],
  ["bien", "well, good"],
  ["porque", "because"],
  ["nada", "nothing"],
  ["sé", "I know"],
  ["hacer", "to do, to make"],
  ["tiene", "has (he/she/it)"],
  ["hay", "there is, there are"],
  ["ahora", "now"],
  ["ser", "to be"],
  ["mucho", "much, a lot"],
  ["cuando", "when"],
    ["también", "also, too"],
    ["vez", "time (occurrence)"],
    ["sí", "yes"],
    ["nos", "us, ourselves"],
    ["ver", "to see"],
    ["esto", "this (neuter)"],
    ["este", "this (masculine)"],
    ["algo", "something"],
    ["ese", "that (masculine)"],
    ["ahí", "there"],
    ["mejor", "better, best"],
    ["dos", "two"],
    ["cómo", "how"],
    ["vamos", "we go, let's go"],
    ["tengo", "I have"],
    ["esa", "that (feminine)"],
    ["tiempo", "time, weather"],
    ["día", "day"],
    ["voy", "I go, I am going"],
    ["bueno", "good, well"],
    ["fue", "was (he/she/it), went (he/she/it)"],
    ["puede", "can (he/she/it), may (he/she/it)"],
    ["todos", "all, everyone"],
    ["era", "was (I/he/she/it)"],
    ["hace", "does, makes (he/she/it), ago"],
    ["les", "them, to them"],
    ["va", "goes (he/she/it)"],
    ["pasa", "happens, passes (he/she/it)"],
    ["siempre", "always"],
    ["otra", "another, other (feminine)"],
    ["uno", "one"],
    ["estoy", "I am"],
    ["quiero", "I want"],
    ["estar", "to be"],
    ["están", "are (they)"],
    ["hasta", "until, even"],
    ["estaba", "was (I/he/she/it)"],
    ["sin", "without"],
    ["gracias", "thanks, thank you"],
    ["él", "he, him"],
    ["quién", "who"],
    ["vida", "life"],
    ["dónde", "where"],
    ["cosas", "things"],
    ["creo", "I believe, I think"],
    ["tenemos", "we have"],
    ["otro", "another, other (masculine)"],
    ["aquí", "here"],
    ["mí", "me (object)"],
    ["ni", "neither, nor"],
    ["solo", "only, alone"],
    ["nunca", "never"],
    ["verdad", "truth"],
    ["nosotros", "we, us"],
    ["tres", "three"],
    ["estás", "you are"],
    ["puedo", "I can, I am able"],
    ["ir", "to go"],
    ["tener", "to have"],
    ["tu", "your"],
    ["gente", "people"],
    ["decir", "to say, to tell"],
    ["estamos", "we are"],
    ["mis", "my (plural)"],
    ["soy", "I am"],
    ["entonces", "then, so"],
    ["casa", "house, home"],
    ["después", "after, later"],
    ["poco", "little, few"],
    ["favor", "favor"],
    ["tan", "so (intensity)"],
    ["nadie", "nobody, no one"],
    ["antes", "before"],
    ["años", "years"],
    ["vas", "you go, you are going"],
    ["van", "they go, they are going"],
    ["mismo", "same, self"],
    ["hoy", "today"],
    ["desde", "from, since"],
    ["quiere", "he/she wants"],
    ["sus", "his, her, their (plural)"],
    ["toda", "all, whole (feminine)"],
    ["cosa", "thing"],
    ["sea", "be (subjunctive)"],
    ["momento", "moment"],
    ["menos", "less, minus"],
    ["cuenta", "account, bill, realizes"],
    ["da", "gives (he/she/it)"],
    ["ella", "she, her"],
    ["claro", "clear, of course"],
    ["mañana", "tomorrow, morning"],
    ["días", "days"],
    ["unos", "some, a few"],
    ["sabe", "he/she knows"],
    ["dije", "I said"],
    ["dice", "he/she says"],
    ["tenía", "I/he/she had"],
    ["ha", "has (he/she/it)"],
    ["hablar", "to talk, to speak"],
    ["parece", "it seems, looks like"],
    ["gusta", "likes (he/she/it)"],
    ["alguien", "someone, somebody"],
    ["quería", "I/he/she wanted"],
    ["muchas", "many (feminine)"],
    ["donde", "where"],
    ["había", "there was, there were"],
    ["mundo", "world"],
    ["tanto", "so much, so many"],
    ["pasó", "happened, passed (he/she/it)"],
    ["salir", "to leave, to go out"],
    ["veces", "times (occurrences)"],
    ["viene", "comes (he/she/it)"],
    ["todas", "all (feminine)"],
    ["dar", "to give"],
    ["tal", "such, like that"],
    ["hecho", "fact, done, made"],
    ["pasar", "to pass, to happen"],
    ["noche", "night"],
    ["igual", "equal, same, alike"],
    ["estos", "these (masculine)"],
    ["cada", "each, every"],
    ["haciendo", "doing, making"],
    ["iba", "was going, used to go"],
    ["hombre", "man"],
    ["saber", "to know"],
    ["podemos", "we can, we are able"],
    ["tienen", "they have"],
    ["tú", "you"],
    ["hola", "hello"],
    ["madre", "mother"],
    ["trabajo", "work, job"],
    ["fuera", "outside, out, were (subjunctive)"],
    ["mira", "look (he/she/it)"],
    ["dijo", "he/she said"],
    ["digo", "I say"],
    ["tus", "your (plural)"],
    ["buena", "good (feminine)"],
    ["seguro", "sure, safe, insurance"],
    ["mal", "bad, wrong"],
    ["ellos", "they (masculine)"],
    ["casi", "almost"],
    ["entre", "between, among"],
    ["conmigo", "with me"],
    ["único", "only, unique"],
    ["veo", "I see"],
    ["hora", "hour, time"],
    ["cinco", "five"],
    ["siento", "I feel, I am sorry"],
    ["dejar", "to leave, to let"],
    ["todavía", "still, yet"],
    ["haber", "to have (auxiliary verb)"],
    ["falta", "lack, absence, missing"],
    ["hijo", "son"],
    ["ve", "go (imperative), he/she sees"],
    ["tampoco", "neither, nor, either"],
    ["parte", "part, portion"],
    ["llegar", "to arrive, to reach"],
    ["cuatro", "four"],
    ["eh", "eh?, huh?"],
    ["sabes", "you know"],
    ["he", "I have (auxiliary verb)"],
    ["venir", "to come"],
    ["somos", "we are"],
    ["ah", "ah, oh"],
    ["familia", "family"],
    ["esos", "those (masculine)"],
    ["hago", "I do, I make"],
    ["unas", "some (feminine)"],
    ["queda", "remains, is left, stays"],
    ["buen", "good (shortened form of bueno)"],
    ["además", "besides, furthermore"],
    ["luego", "then, later"],
    ["ven", "come (imperative)"],
    ["tarde", "late, afternoon, evening"],
    ["buenas", "good (feminine, shortened form of buenas tardes/noches)"],
    ["primero", "first (masculine)"],
    ["señor", "Mr., sir"],
    ["lugar", "place, location"],
    ["nuestro", "our (masculine)"],
    ["sabía", "I/he/she knew"],
    ["pues", "well, then"],
    ["primera", "first (feminine)"],
    ["sobre", "about, on, over"],
    ["ves", "you see"],
    ["usted", "you (formal)"],
    ["amor", "love"],
    ["cualquier", "any, whichever"],
    ["nuestra", "our (feminine)"],
    ["tienes", "you have"],
    ["necesito", "I need"],
    ["allá", "there, over there"],
    ["dios", "God"],
    ["importante", "important"],
    ["ay", "oh, ouch"],
    ["sido", "been"],
    ["eres", "you are"],
    ["mujer", "woman"],
    ["venga", "come (subjunctive/imperative)"],
    ["han", "they have (auxiliary verb)"]
]);
