const dict = new Map([
    ["ability", "khả năng"],
    ["able", "có thể, có khả năng"],
    ["abroad", "ở nước ngoài"],
    ["accept", "chấp nhận"],
    ["accident", "tai nạn"],
    ["according to", "theo"],
    ["achieve", "đạt được"],
    ["act", "hành động"],
    ["active", "hoạt động, năng động"],
    ["actually", "thực ra"],
    ["adult", "người lớn"],
    ["advantage", "lợi thế"],
    ["adventure", "cuộc phiêu lưu"],
    ["advertise", "quảng cáo"],
    ["advertisement", "quảng cáo (danh từ)"],
    ["advertising", "quảng cáo (ngành nghề)"],
    ["affect", "ảnh hưởng"],
    ["after", "sau khi"],
    ["against", "chống lại"],
    ["ah", "à (thán từ)"],
    ["airline", "hãng hàng không"],
    ["alive", "còn sống"],
    ["all", "tất cả"],
    ["all right", "ổn, được"],
    ["allow", "cho phép"],
    ["almost", "gần như"],
    ["alone", "một mình"],
    ["along", "dọc theo"],
    ["already", "đã"],
    ["alternative", "thay thế"],
    ["although", "mặc dù"],
    ["among", "giữa, trong số"],
    ["amount", "số lượng"],
    ["ancient", "cổ đại"],
    ["ankle", "mắt cá chân"],
    ["any", "bất kỳ"],
    ["anybody", "bất kỳ ai"],
  ["any more", "không còn nữa"],
  ["anyway", "dù sao đi nữa"],
  ["anywhere", "bất cứ nơi nào"],
  ["app", "ứng dụng"],
  ["appear", "xuất hiện"],
  ["appearance", "vẻ bề ngoài"],
  ["apply", "áp dụng, nộp (đơn)"],
  ["architect", "kiến trúc sư"],
  ["architecture", "kiến trúc"],
  ["argue", "tranh luận"],
  ["argument", "cuộc tranh luận"],
  ["army", "quân đội"],
  ["arrange", "sắp xếp"],
  ["arrangement", "sự sắp xếp"],
  ["as", "như, khi"],
  ["asleep", "ngủ, đang ngủ"],
  ["assistant", "trợ lý"],
  ["athlete", "vận động viên"],
  ["attack", "tấn công"],
  ["attend", "tham dự"],
  ["attention", "chú ý"],
  ["attractive", "hấp dẫn"],
  ["audience", "khán giả"],
  ["author", "tác giả"],
  ["available", "có sẵn"],
  ["average", "trung bình"],
  ["avoid", "tránh"],
  ["award", "giải thưởng"],
  ["awful", "kinh khủng"],
  ["back", "phía sau, trở lại"],
  ["background", "nền, xuất thân"],
  ["badly", "tệ, nghiêm trọng"],
  ["bar", "quán bar, thanh"],
  ["baseball", "bóng chày"],
  ["based", "dựa trên"],
  ["basketball", "bóng rổ"],
  ["bean", "hạt đậu"],
  ["bear (animal)", "con gấu"],
  ["beat", "đánh bại"],
  ["beef", "thịt bò"],
  ["before", "trước khi"],
  ["behave", "cư xử"],
  ["behaviour", "hành vi"],
  ["belong", "thuộc về"],
  ["belt", "thắt lưng"],
  ["benefit", "lợi ích"],
  ["best", "tốt nhất"],
  ["better", "tốt hơn"],
  ["between", "giữa"],
  ["billion", "tỷ"],
  ["bin", "thùng rác"],
  ["biology", "sinh học"],
  ["birth", "sinh, sự ra đời"],
  ["biscuit", "bánh quy"],
  ["bit", "một chút"],
  ["blank", "trống, để trống"],
  ["blood", "máu"],
  ["blow", "thổi"],
  ["board", "bảng, lên (tàu, máy bay)"],
  ["boil", "đun sôi"],
  ["bone", "xương"],
  ["book", "đặt (chỗ)"],
  ["borrow", "mượn"],
  ["boss", "ông chủ"],
  ["bottom", "đáy, dưới cùng"],
  ["bowl", "bát"],
  ["brain", "bộ não"],
  ["bridge", "cầu"],
  ["bright", "sáng, thông minh"],
  ["brilliant", "xuất sắc, rực rỡ"],
  ["broken", "bị hỏng, vỡ"],
  ["brush", "chải, bàn chải"],
  ["burn", "đốt, cháy"],
  ["businessman", "doanh nhân"],
  ["button", "nút, cúc"],
  ["camp", "trại, cắm trại"],
  ["camping", "việc cắm trại"],
  ["can", "lon, hộp thiếc"],
  ["care", "chăm sóc, quan tâm"],
  ["careful", "cẩn thận"],
  ["carefully", "một cách cẩn thận"],
  ["carpet", "thảm"],
  ["cartoon", "phim hoạt hình, truyện tranh"],
  ["case", "trường hợp, hộp"],
  ["cash", "tiền mặt"],
  ["castle", "lâu đài"],
  ["catch", "bắt, chộp"],
  ["cause", "nguyên nhân, gây ra"],
  ["celebrate", "ăn mừng, kỷ niệm"],
  ["celebrity", "người nổi tiếng"],
  ["certain", "chắc chắn, nhất định"],
  ["certainly", "chắc chắn"]
  ]);
  